# Generated by Django 4.1.3 on 2022-11-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('claveCarrera', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreCarrera', models.CharField(max_length=50)),
                ('numeroCreditos', models.IntegerField()),
                ('numeroSemestres', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('numeroPersonal', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50)),
                ('tipoDocente', models.CharField(choices=[('Profesor', 'Profesor'), ('Jefe de departamento', 'Jefe de departamento'), ('Coordinador de carrera', 'Coordinador de carrera')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('numeroControl', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50)),
                ('semestre', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosEscolares.carreras')),
            ],
        ),
    ]
