# Generated by Django 4.1.3 on 2022-11-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosEscolares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='numeroControl',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='matricula',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carreras',
            name='Coordinador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serviciosEscolares.docentes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docentes',
            name='correoInstitucional',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='semestre',
            field=models.CharField(max_length=50),
        ),
    ]
