# Generated by Django 4.1.3 on 2022-11-16 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosEscolares', '0002_remove_alumnos_numerocontrol_alumnos_matricula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('claveDepartamento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=50)),
                ('tipoDepartamento', models.CharField(choices=[('Administrativo', 'Administrativo'), ('Academico', 'Academico')], max_length=50)),
                ('jefeDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosEscolares.docentes')),
            ],
        ),
        migrations.CreateModel(
            name='Tramites',
            fields=[
                ('claveTramite', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTramite', models.CharField(max_length=50)),
                ('descripcionTramite', models.CharField(max_length=50)),
                ('tipoTramite', models.CharField(choices=[('Inscripcion', 'Inscripcion'), ('Reinscripcion', 'Reinscripcion'), ('Cambio de carrera', 'Cambio de carrera')], max_length=50)),
                ('estadoTramite', models.CharField(choices=[('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado')], max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('observaciones', models.CharField(max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosEscolares.alumnos')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosEscolares.departamentos')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosEscolares.docentes')),
            ],
        ),
    ]
